name: Medium Biomes Legacy
version: 1.0.0

pipeline:
  - src.plugins.noise

meta:
  base_version: "1.19"

data_pack:
  load: src/datapack
  description: {"text":"Medium Biomes\n1.19 - 1.21.8", "color":"gray"}
  pack_format: 10
  supported_formats:
    min_inclusive: 10
    max_inclusive: 81

output: build