name: Medium Biomes
version: 0.2.0

pipeline:
  - src.plugins.noise

meta:
  base_version: "1.21.9"

data_pack:
  load: src/datapack
  description: {"text":"Medium Biomes\n1.21.9 - 26.1", "color":"gray"}
  min_format: 82
  max_format: 101

output: build