name: Medium Biomes
version: 0.2.0

pipeline:
  - src.plugins.noise

meta:
  base_version: "1.19" # Do not set to 1.18 => beet doesn't support this version.

data_pack:
  load: src/datapack
  description: {"text":"Medium Biomes\n1.18 - 26.1", "color":"gray"}
  pack_format: 8
  min_format: 8
  max_format: 101
  supported_formats:
    min_inclusive: 8
    max_inclusive: 101

output: build
