name: Medium Biomes
version: 0.1.0

pipeline:
  - beet.contrib.render

meta:
  render:
    data_pack:
      - "**"

data_pack:
  description: {"text":"Medium Biomes\n1.20 - 26.1", "color":"gray"}
  pack_format: 15
  min_format: 15
  max_format: 101
  supported_formats:
    min_inclusive: 15
    max_inclusive: 101
  load: src/datapack

output: build
